### ISSUE TITLE
Feedback - Week 13 Assignment

### ISSUE THREAD

**Issue by ntuvera** [Mark-A-A/Mark_Portfolio-RCBSaturday#21]
Hey @Mark-A-A, what's up?  I cloned your repo and started poking around...

Looking through your code, I see you've done the static routes, but we're missing dynamic routes.  I'm sure you're comfortable making them (correct me if I'm wrong), but the new question is... to what? lol  Well that's a design choice either way, but I need to see it in the assignment.  

Beyond that, I see you required `express-session`, but didn't use it anywhere.  Once again, this is one of those I just need to see it.  It really does nothing on your portfolio page unless you want to be all big brother about it and build on to it.  

I also noticed you're console.logging on your get routes.  Each. Route.  This sounds like a good place to build some kind of middleware function, which will be helpful for practice and also some meaningful output in console, without writting similar lines over and over.

Another part of the assignment was to include your RPS and/or you're Clicky game, which I'm not seeing in it's own route or in a dynamic route ;)  But the most important part is that we've replaced the `index.php` and `composer.json` with a real node server.  I'm sure you'll build on this, it's just a matter of time.  But don't forget to check the homework instructions and "check off the boxes".

Polish up your portfolio page, I know you can, I just want to see it.

Good Luck on Project Week.

**Comment by Mark-A-A** [comment]
polishing up with complete upgrade
